language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
  allow_failures:
      - php: hhvm

install:
    - composer install --prefer-source --no-dev -o

script:
    - phpunit --coverage-text --coverage-clover clover.xml

after_script:
    - wget https://github.com/satooshi/php-coveralls/releases/download/v0.7.1/coveralls.phar
    - php coveralls.phar

