language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer install --prefer-source --no-dev --no-interaction -o

script:
    - phpunit --coverage-text --coverage-clover clover.xml

after_script:
    - chmod +rwx clover.xml
    - wget https://github.com/satooshi/php-coveralls/releases/download/v0.7.1/coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar

