language: php

php:
    - 5.4
    - 5.5

before_script:
    - composer self-update
    - composer install --prefer-source -o

script:
    - bin/phpunit --coverage-text --coverage-clover clover.xml

after_script:
    - bin/coveralls

