language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - 8.0

sudo: false

install:
    - travis_retry composer install --prefer-source --no-interaction

script:
    - phpunit --coverage-text --coverage-clover clover.xml

after_script:
    - chmod +rwx clover.xml
    - wget https://github.com/satooshi/php-coveralls/releases/download/v0.7.1/coveralls.phar
    - php coveralls.phar

